fecitec/static/Css/style.css, fecitec/templates/base.html, fecitec/views.py
adicionei a animação no navbar
=> adicionando animação no navabar

fecitec/static/Css/aprovados.css, fecitec/templates/aprovado.html, fecitec/templates/base.html, fecitec/views.py
Terminei a estilização da tela dos trabalhos  aprovados ( mídias menores ainda sem ajustes )
=> finalizando tela de aprovados

fecitec/templates/base.html, fecitec/urls.py, fecitec/views.py
adicionei todas as views que faltavam
=> adicionando views

fecitec/static/Css/Midias/bigDesktop.css, fecitec/static/Css/Midias/notebook.css, fecitec/static/Css/Midias/phone.css, fecitec/static/Css/Midias/tablet.css, fecitec/static/Css/style.css, fecitec/templates/base.html
Crie o menu hamburguer que ficara visível apenas em mídias menores. ( funcional )
=> Menu Hamburguer Responsivo

fecitec/static/Css/cronograma.css, fecitec/static/Css/home.css, fecitec/static/Css/style.css, fecitec/templates/cronograma.html
Criei os cards da página de cronograma do projeto
=> Criação da página cronograma

fecitec/static/Css/cronograma.css, fecitec/static/Css/home.css, fecitec/static/Css/mapa.css, fecitec/templates/cronograma.html, fecitec/templates/home.html, fecitec/templates/partials/mapa.html
criei uma pasta "partials" e dentro dela um arquivo único para o mapa, criei um arquivo css para o mapa, adicionei o mapa na págoina de cronograma
=> Adicionando mapa na página de cronograma

fecitec/templates/certificados.html, fecitec/templates/comissao.html, fecitec/templates/contate.html, fecitec/templates/login.html, fecitec/templates/regulamento.html, fecitec/templates/submissao.html
adicionei o template base nas em todas as páginas HTML que faltavam e criei o CSS das páginas que faltavam
=> adicionando base nas paginas

fecitec/static/Css/Midias/phone.css, fecitec/static/Css/aprovados.css, fecitec/static/Css/style.css, fecitec/templates/aprovado.html
Adicionei um scroll lateral na tabela de aprovados
=> Correcao scroll table 

fecitec/static/Css/Midias/Phone/aprovados-phone.css, fecitec/templates/aprovado.html
corrigir a tela de aprovados na versão de celular
=> Tela de aprovados(Phone) finalizado

fecitec/static/Css/Midias/BigDesktop/comissao-bigDesktop.css, fecitec/static/Css/comissao.css, fecitec/templates/comissao.html
finalizei o estilo dos cards dos colaboradores e ajustei a responsividade para notebooks
=> finalizando estilo dos cards

fecitec/static/Css/Midias/Phone/aprovados-phone.css, fecitec/static/Css/aprovados.css, fecitec/static/Css/certificados.css, fecitec/static/Css/regulamento.css, fecitec/static/Css/style.css, fecitec/templates/base.html, fecitec/templates/regulamento.html
Finalizei as telas Aprovados e Certificados para mídias maiores ;
Crie a tela Regulamento juntamente do acordeom de informações
=> Criação da Tela Regulamento

fecitec/static/Css/Midias/Phone/certificados-phone.css, fecitec/static/Css/aprovados.css, fecitec/static/Css/certificados.css, fecitec/static/Css/regulamento.css, fecitec/static/Js/acordion.js, fecitec/templates/base.html, fecitec/templates/certificados.html, fecitec/templates/regulamento.html
1. Crie o acordeom com JavaScript  e estilizei ele conforme o projeto Figma  ;
2. Reajustei alguns detalhes algum detalhes de mídias das tabelas aprovados, certificados e premiados
=> Criação do estilo do acordeom (não finalizado)

fecitec/static/Css/Midias/Phone/comissao-phone.css, fecitec/static/Css/comissao.css, fecitec/templates/comissao.html
finalizei a paginação dos colaboradores e deixei responsivo para dispositivos menores
=> finalizando paginação

fecitec/static/Css/login.css, fecitec/templates/login.html
1. Crie  a tela de login e a estilizei
=> Criacao da tela Login

fecitec/static/Css/Midias/Phone/contate-phone.css, fecitec/static/Css/Midias/Tablet/contate-tablet.css, fecitec/static/Css/contate.css, fecitec/templates/contate.html, fecitec/templates/submissao.html
Criei a pagina de contato e a deixei responsiva para smartphones e tablets
=> criando pagina de contato

fecitec/static/Css/style.css, fecitec/templates/base.html
adicionei o link ativo ao navbar
=> adicionando ativo ao navbar

fecitec/templates/base.html
adicionei o title na seta que faz voltar ao topo da pagina
=> adicionando title na seta

fecitec/static/Css/Midias/Phone/login-phone.css, fecitec/static/Css/Midias/Tablet/login-tablet.css, fecitec/static/Css/Midias/Tablet/tablet.css, fecitec/static/Css/login.css, fecitec/static/Js/select-dropdonw.js, fecitec/static/images/icone-seta-para-baixo.svg, fecitec/templates/base.html, fecitec/templates/login.html
1. crie o menu dropdonw da tela de login
2. finalizei a responsividade da tela de login para todas as midias
=> tela de login finalizada e responsiva

fecitec/static/Css/comissao.css, fecitec/static/Css/cronograma.css, fecitec/static/Css/home.css, fecitec/templates/comissao.html, fecitec/templates/contate.html, fecitec/templates/cronograma.html, fecitec/templates/home.html, fecitec/templates/submissao.html
=> adicionando titulos

fecitec/static/Css/Midias/Tablet/regulamento-tablet.css, fecitec/static/Css/login.css, fecitec/static/Css/regulamento.css, fecitec/templates/regulamento.html
1. Fiz a estilização do dropdown da tela de regulamento ( nao estilizado em midias menores )
=> Correção Estilo do Regulamento

fecitec/static/Css/Midias/Phone/phone.css, fecitec/static/Css/style.css, fecitec/templates/base.html
1. crie e estilizei um novo banner (não finalizado em mídias menores )
=> Crie um novo banner(Não Finalizado)

fecitec/static/Css/aprovados.css, fecitec/static/Css/certificados.css, fecitec/static/Css/contate.css, fecitec/static/Css/cronograma.css, fecitec/static/Css/login.css, fecitec/static/Css/mapa.css, fecitec/static/Css/submissao.css, fecitec/templates/contate.html, fecitec/templates/submissao.html
ajustei a largura de alguns campos para que ficassem iguais
=> ajustando largura dos campos

fecitec/static/Css/Midias/Phone/phone.css, fecitec/static/Css/style.css
1. Finalizei a estilização do novo banner para celular e tablets
=> Novo banner

fecitec/static/Css/contate.css, fecitec/static/Css/style.css, fecitec/templates/base.html, fecitec/templates/contate.html
adicionei um novo estilo ao navbar e removi algumas classes que não estavam sendo utilizadas
=> adicionando novo estilo ao navbar

fecitec/templates/base.html, fecitec/templates/formigueiro.html, fecitec/urls.py, fecitec/views.py
ajustei as rotas de urls.py e adicionei uma nova rota chamada formigueiro
=> ajustando e criando novas rotas

fecitec/static/Css/formigueiro.css, fecitec/templates/formigueiro.html
criei as configurações iniciais da pagina do formigueiro
=> criando pagina do formigueiro(incompleta)

fecitec/static/Css/Midias/Phone/cronograma-phone.css, fecitec/static/Css/Midias/Phone/home-phone.css, fecitec/static/Css/Midias/Phone/phone.css, fecitec/static/Css/Midias/Phone/submissao-phone.css, fecitec/static/Css/Midias/Tablet/tablet.css, fecitec/static/Css/cronograma.css, fecitec/static/Css/mapa.css, fecitec/templates/base.html, fecitec/templates/cronograma.html
escondi a navbar em dispositivos menores que notebook, ajustei a largura do mapa em dispositivos menores e ajustei a responsvidade da tela de cronograma
=> resolvendo erros de estilo

fecitec/forms.py, fecitec/static/Css/contate.css, fecitec/templates/contate.html, fecitec/urls.py, fecitec/views.py
criei as configurações básicas do models form de contato para envio de email
=> criando models form de contato

fecitec/static/Css/login.css, fecitec/templates/login.html, fecitec/views.py
1. Crie uma verificação de campos para o formulário de login ( nome , senha, função )
=> Terminei a avaliação dos campos do formulário de login

fecitec/forms.py, fecitec/static/Css/contate.css, fecitec/templates/comissao.html, fecitec/templates/contate.html, fecitec/urls.py, setup/settings.py
conclui as configurações do form de contato
=> concluindo form de contato

fecitec/static/Css/Midias/Phone/submissao-phone.css
ajustei a responsividade da pagina de submissao
=> ajustando responsividade da pagina de submmissao

fecitec/static/Css/Midias/Phone/formigueiro-phone.css, fecitec/static/Css/Midias/Tablet/formigueiro-tablet.css, fecitec/static/Css/formigueiro.css, fecitec/templates/formigueiro.html
1. Estilizei a tela de portifólio para midias menores
=> Estilização tela formigueiro (Mídias menores)

admin_fecitec/static/Css/style_admin.css, admin_fecitec/static/Js/profile-user.js, admin_fecitec/templates/base_admin.html, admin_fecitec/urls.py, fecitec/static/images/icone-pencil.svg, setup/settings.py
1. Terminei a estilização do banner de outras contas 
2. Adição de um modal para opções de perfil
3. Adição da opção logout ( "Funcional ")
=> Add profile modal and styles; improve user logout handling

admin_fecitec/static/Css/style_admin.css, fecitec/views.py
1. Iniciei a criação da navbar alternada do administrador.
2. Corrigir o erra do login quando o usuário pertence a duas funções.
=> Atualiza estilo da na bar e ajusta lógica de login do usuário

admin_fecitec/static/Css/style_admin.css, admin_fecitec/views.py, fecitec/views.py
Estou tentado evitar que o usuario sem login copie e cole um rota urls de administrador
=> Correcao de seguranca de  Urls

core/admin.py, core/apps.py, core/models.py, core/tests.py, core/views.py, setup/settings.py
criei o app core para centralizar o models de todas as aplicações
=> criando app core

fecitec/static/Css/Midias/Phone/submissao-phone.css, fecitec/static/Css/submissao.css, fecitec/templates/submissao.html
criei o botão da área de submissão
=> criando botao de sumissão

fecitec/templates/base.html, fecitec/templates/login_participante.html, fecitec/urls.py, fecitec/views.py
Crie um template para o usuário Participante
=> Novo login para participante

fecitec/static/Css/login.css, fecitec/static/Js/switchLoginForms.js, fecitec/templates/login_participante.html
1. Adição do script para alternar entre os formulários de login participante e criar conta de participante
=> Refatoração do formulário de login e criação de conta

fecitec/static/Css/Midias/Phone/submissao-phone.css, fecitec/static/Css/login.css, fecitec/static/Css/style.css, fecitec/static/Css/submissao.css, fecitec/static/Js/selected-file.js, fecitec/static/Js/switch-pages.js, fecitec/templates/base.html, fecitec/templates/submissao.html
Criei a área de submissão de trabalho(incompleta)
=> criando área de submissão de trabalho(incompleta)

app_participante/admin.py, app_participante/apps.py, app_participante/models.py, app_participante/tests.py, app_participante/urls.py, app_participante/views.py, core/views.py, setup/settings.py
1. Crie e configurei uma app para o participante
=> App para Participantes

admin_fecitec/views.py, core/admin.py, core/models.py, fecitec/views.py
1. Lógica de autenticação: Integrei o modelo GrupoPersonalizado e simplifiquei o controle de acesso.
2. Modelo GrupoPersonalizado: Adicionei sinais e melhorei a manipulação de usuários.
3. Ajustes nas views: Atualizei redirecionamentos e removi redundâncias no código.
4. Administração do Django: Incluí filter_horizontal para facilitar a seleção de usuários no admin do Django.
=> Refatora autenticação e ajusta permissões nas views e modelo.

fecitec/static/Css/submissao.css, fecitec/templates/submissao.html
criei o estilo do form da área de submissão de trabalho
=> criando form de submissão de trabalho

fecitec/static/Css/login.css, fecitec/static/Css/style.css, fecitec/static/Js/switchLoginForms.js, fecitec/templates/base.html, fecitec/templates/login.html, fecitec/templates/login_participante.html
1. Refatoração do layout e novos estilos para a página de login e cadastro, 
2. incluindo ajustes de responsividade, 
3. novos formulários e links para login da comissão.
=> Ajustes no layout e funcionalidade dos formulários de login

fecitec/static/Css/Midias/Phone/submissao-phone.css, fecitec/static/Css/Midias/Tablet/submissao-tablet.css, fecitec/static/Css/submissao.css, fecitec/templates/submissao.html
deixei o  formulário de submissão de trabalho responsivo para todos os dispositivos
=> ajustando responsividade do formulario de submissao de trabalho

fecitec/templates/cadastro_participante.html
.Retirei a duplicidade dos campos causados por o {{forms_p}}
=> Correção no campos de cadastro de Praticante

core/forms.py, core/models.py, core/views.py
1. Corrigir o erro de usuário com nomes iguais 
2. Corrigir o erro do nome da instituição
3. Usuário ao criar a conte ja esta sendo atribuído a group participante
=> Login/Cadrastro participante( 100% funcional )

fecitec/static/Css/submissao.css, fecitec/static/Js/error-message.js, fecitec/static/Js/selected-file.js, fecitec/templates/base.html, fecitec/templates/submissao.html, fecitec/views.py
finalizei a parte visual da área de submssão
=> finalizando parte visual da área de submissão

core/models.py, core/views.py, fecitec/templates/cadastro_participante.html
1. Corrigir o erro que ao criar o usuário não o incluía no grupo participante
=> Correcao de erro de dublicidade ao cria participante

fecitec/forms.py, fecitec/static/Js/number-mask.js, fecitec/templates/contate.html
criei a mascara do número para contato
=> criando mascara para número de contato

fecitec/static/Css/style.css, fecitec/templates/base.html
adicionei o campo de visitas no footer do template base
=> adicioando campo de visitas

admin_fecitec/views.py, fecitec/static/Css/Midias/Phone/login-phone.css, fecitec/static/Css/Midias/Tablet/login-tablet.css, fecitec/templates/cadastro_participante.html, fecitec/views.py
1.  Ajustes nos estilos dos formulários para mobile e tablet.
2.  Correções no template 'cadastro_participante.html'.
3. Simplificação e melhorias no código de 'views.py' e 'admin_fecitec/views.py'.
=> Atualizações no CSS, template de cadastro e views do projeto

fecitec/static/Css/Midias/Phone/submissao-phone.css, fecitec/static/Css/style.css, setup/settings.py
ajustei a responsividade do formulario de submissão que estava quebrando
=> ajustando responsividade da área de submissão

app_participante/templates/base_participante.html
fiz as configurações iniciais da página do paticipante
=> configurando front-end inicial da página do participante

app_participante/static/Css/dashb_participante.css, app_participante/templates/base_participante.html, app_participante/templates/dashboard_participante.html
criei o front end inicial da página do participante
=> criando front end inicial da pagina do participante

core/forms.py, core/models.py, core/views.py, fecitec/templates/cadastro_participante.html, fecitec/urls.py, fecitec/views.py
1. realoquei a views de cadastro de participante para o app Fecitec 
2. criei a chave primaria e estrangeira na relação do participante e instituição 
3. adicionei o select no hmtl de cadastro
=> Mudança na views de cadastro de participante

core/forms.py, fecitec/static/Css/login.css, fecitec/templates/cadastro_participante.html, fecitec/views.py
1. adição de campos como nome de usuário, e-mail, 
2. senha e celular com novos placeholders; 
3. ajustes no CSS de login; 
4. atualização da página de cadastro para utilizar campos dinâmicos do Django.
=> Alterações no formulário de cadastro de participante: 

app_participante/static/Css/dashb_participante.css, app_participante/static/Js/dropdown.js, app_participante/templates/base_participante.html, app_participante/templates/dashboard_participante.html, fecitec/forms.py, fecitec/static/Css/submissao.css, fecitec/templates/submissao.html, fecitec/views.py
criei a tabela para exibir as submissões do usuario logado com as opções de "editar" e "cancelar" faltando somente a responsividade da tabela para dispositivos mobiles
=> ajustes na página do participante

app_participante/static/Css/dashb_participante.css, app_participante/static/Js/dropdown.js
criei o dropdown para a tabela de submissões do participante
=> criando dropdown

app_participante/static/Css/dashb_participante.css
deixei a tabela de submissões do usúario respponsiva
=> deixando tabela de submissoes responsiva

admin_fecitec/static/Css/style_admin.css, setup/settings.py
=> salvando alterações

app_participante/static/Css/submissao_trabalho.css, app_participante/templates/submissao-de-trabalho.html
adicionei o botão de voltar na tela de criar uma submissão
=> adicionando botão de voltar

admin_fecitec/templates/admin_screen_submission.html
corrigi o erro de não estar aparecendo o nome do participante na tabela
=> corrigindo nome do participante na tabela

app_participante/static/Css/Midias/submissao_trabalho_phone.css, app_participante/static/Css/submissao_trabalho.css, app_participante/templates/submissao-de-trabalho.html, fecitec/static/Css/contate.css, fecitec/templates/contate.html
padronizei o label de todos os formularios do sistema
=> padronizando label dos formularios

app_participante/static/Css/Midias/submissao_trabalho_phone.css, app_participante/static/Css/submissao_trabalho.css
deixei a área de submissão responsiva
=> deixando área de submissão responsiva

app_participante/static/Css/dashb_participante.css, app_participante/templates/dashboard_participante.html, app_participante/views.py, fecitec/static/Css/comissao.css, fecitec/templates/comissao.html
criei e estilizei a páginação de submissões do participante
=> criando páginação de submissões do participante

admin_fecitec/templates/admin_screen_participants.html, admin_fecitec/views.py
adicionei a quantidade de submissões de cada participante na tela do administrador
=> adicioando número de submissões na tela do admin

admin_fecitec/static/Css/registered_member.css, admin_fecitec/templates/admin_registered_member_comission.html, admin_fecitec/views.py, core/admin.py, core/forms.py, core/models.py
1. Fiz um estilização bem simples da tela de cadastro dos membros da comissão acadêmica .
2. Funcionalidade de cadastro de usuário (funcionando mas login do usuário cadastrado não ).
=> Estilização da tela de cadastro de membros semifinalizada

admin_fecitec/views.py
Configuração da views de criação de membros da comissão esta quase finalizada(falta algumas validações de error ).
(O ERRO de não conseguir logar com o usuário criado persiste ).
=> Views de criação de membro semifinalizada(90%)

admin_fecitec/static/Css/registered_member.css, admin_fecitec/static/Css/screen_admin_comissao.css, admin_fecitec/templates/admin_registered_member_comission.html, fecitec/static/Css/login.css
Fiz a estilização css dos campos na tela de cadastro de membros da comissão acadêmica (finalizado apenas em Desktop )
- Finalizar em dispositivos moveis (Nao finalizado )
=> Estilização Css da Pagina Cadastro de membros( Finalizado Desktop )

admin_fecitec/static/Css/registered_member.css, admin_fecitec/views.py, core/forms.py, fecitec/views.py
Finalizei a views de cadastro, funcionando 100 %
=> Views de cadastro de membros totalmente funcional

admin_fecitec/static/Css/screen_admin_comissao.css, admin_fecitec/static/Js/modal_edit_member.js, admin_fecitec/views.py
1. Correção na alteração de grupos dos membros da comissão
=> Correção na alteração de grupos dos membros da comissão

app_jurado/static/Css/style_jurado.css, app_jurado/templates/base_jurado.html, app_jurado/templates/dashboard_jurado.html, core/middleware.py, fecitec/views.py
Criei o html base para a tela dos jurados
=> Configuração do html jurados
